#! /bin/bash

# Install all the dependencies for ns-3, as well as a bunch of other random stuff
apt-install gcc g++ python python-dev mercurial bzr gdb valgrind gsl-bin libgsl0-dev libgsl0ldbl flex bison libfl-dev tcpdump sqlite sqlite3 libsqlite3-dev libxml2 libxml2-dev libgtk2.0-0 libgtk2.0-dev vtun lxc uncrustify doxygen graphviz imagemagick python-sphinx dia python-pygraphviz python-kiwi python-pygoocanvas libgoocanvas-dev libboost-signals-dev libboost-filesystem-dev

# Python stuff
apt-install python-scipy ipython python-matplotlib

# LaTeX stuff
# okular works well for viewing PDFs through kile
apt-install texlive texlive-extra-utils texlive-latex-extra kile texlive-publishers texstudio okular

# Random utils I like
apt-install emacs git konsole gimp gparted

# XMBC desktop media center install
# http://wiki.xbmc.org/index.php?title=Installing_XBMC_for_Linux#Ubuntu
apt-install python-software-properties pkg-config
apt-install software-properties-common
sudo add-apt-repository ppa:team-xbmc/ppa
sudo apt-get update
apt-install xbmc
